$root = Split-Path -Parent $PSScriptRoot
$template = Join-Path $root 'custom-ai-development-services.html'
$base = Get-Content $template -Raw -Encoding UTF8
$utf8 = New-Object System.Text.UTF8Encoding $false

function Set-Marker([string]$html, [string]$name, [string]$value) {
  $pattern = "(?s)<!--SVC:$name-->.*?<!--/SVC:$name-->"
  $replacement = "<!--SVC:$name-->$value<!--/SVC:$name-->"
  return [regex]::Replace($html, $pattern, [System.Text.RegularExpressions.MatchEvaluator]{ param($m) $replacement })
}

$pages = @(
  @{ slug='generative-ai-development'; title='Generative AI Development'; short='Generative AI'; meta='Generative AI development company in Canada. Build secure GenAI apps, copilots, and content automation with Acesoft.'; intro='We help organizations adopt generative AI responsibly with prompts, RAG pipelines, and application layers that deliver value while managing cost, quality, and risk.'; h1='Generative <em>AI Development</em><br>for Modern Products'; answer='<strong>Why invest in generative AI development?</strong> AI Developers.ca helps you ship GenAI features with guardrails, evaluation, and integration into your existing products and workflows.'; h2='Generative AI built for production, not demos'; b1='Model selection aligned to use case and budget'; b2='Prompt engineering and evaluation frameworks'; b3='Content and workflow automation at scale'; b4='Policy guardrails and human review loops'; focus='GenAI features that scale with your product and compliance needs.'; cap1t='GenAI applications'; cap1p='Copilots, content engines, and workflow automation.'; cap2t='RAG and data'; cap2p='Grounded outputs with your knowledge base.'; cap3t='Governance'; cap3p='Guardrails, review loops, and cost controls.'; faq1q='Can you use our private data safely?'; faq1a='Yes-RAG, VPC deployment, and access controls keep data within your boundary.'; faq2q='Which models do you support?'; faq2a='OpenAI, Azure OpenAI, Anthropic, and open models-selected per use case.'; ctat='Ready to build generative AI?'; ctap='Share your use case and we will outline a practical pilot-to-production path.'; tags=@('Generative AI','RAG and copilots','Canada and USA','Enterprise guardrails') },
  @{ slug='llm-development'; title='LLM Development'; short='LLM'; meta='LLM development services in Canada. Custom LLM apps, RAG, fine-tuning, and enterprise deployment by Acesoft.'; intro='Our LLM engineering team builds production-grade language model experiences combining retrieval, tool use, and observability so assistants stay accurate and maintainable.'; h1='LLM <em>Development</em><br>That Stays Accurate at Scale'; answer='<strong>Why dedicated LLM development?</strong> Production LLM apps need RAG, routing, evals, and ops-not just API calls. We engineer the full stack for reliability.'; h2='LLM systems engineered for enterprise products'; b1='RAG and vector search implementation'; b2='Multi-model routing and fallback strategies'; b3='Latency and cost optimization'; b4='Hallucination reduction and quality metrics'; focus='LLM capacity for assistants, search, and automation in your product.'; cap1t='LLM features'; cap1p='Chat, search, and tool-using assistants.'; cap2t='RAG pipelines'; cap2p='Ingestion, indexing, and retrieval quality.'; cap3t='MLOps for LLMs'; cap3p='Evals, monitoring, and continuous improvement.'; faq1q='Do you fine-tune models?'; faq1a='When RAG is not enough, we fine-tune with your data under strict governance.'; faq2q='How do you reduce hallucinations?'; faq2a='Grounding, citations, eval harnesses, and human review for high-risk flows.'; ctat='Ready to build LLM products?'; ctap='Tell us about your users, data, and success metrics-we will propose a delivery plan.'; tags=@('LLM apps','RAG systems','Canada and USA','Production MLOps') },
  @{ slug='ai-agent-development'; title='AI Agent Development'; short='AI Agents'; meta='AI agent development in Canada. Build workflow agents, tool-using copilots, and enterprise automation with Acesoft.'; intro='We design AI agents that plan, call tools, and complete business processes with clear boundaries, audit trails, and approval steps where risk requires human control.'; h1='AI <em>Agent Development</em><br>With Tools and Oversight'; answer='<strong>What makes a production AI agent?</strong> Agents need orchestration, secure tool access, logging, and escalation-not unconstrained autonomy. We build both.'; h2='Agents that complete work safely in your environment'; b1='Agent workflow design and orchestration'; b2='Secure tool and API integrations'; b3='Error handling and escalation paths'; b4='Testing for edge cases and failure modes'; focus='Workflow agents for operations, support, and internal automation.'; cap1t='Agent workflows'; cap1p='Multi-step tasks with clear boundaries.'; cap2t='Tool integrations'; cap2p='CRM, ticketing, APIs, and internal systems.'; cap3t='Observability'; cap3p='Logs, approvals, and audit trails.'; faq1q='Can agents call our internal APIs?'; faq1a='Yes-with permission models, secrets management, and scoped credentials.'; faq2q='How do you handle failures?'; faq2a='Retries, fallbacks, human handoff, and alerting are designed into every workflow.'; ctat='Ready to deploy AI agents?'; ctap='Describe the process you want to automate-we will scope an agent pilot.'; tags=@('AI agents','Tool use','Canada and USA','Audit trails') },
  @{ slug='ai-chatbot-development'; title='AI Chatbot Development'; short='AI Chatbots'; meta='AI chatbot development company Canada. Enterprise chatbots, support bots, and knowledge assistants by Acesoft.'; intro='We build chatbots that understand context, cite sources, and integrate with your knowledge base to improve deflection, response time, and customer satisfaction.'; h1='AI <em>Chatbot Development</em><br>That Deflect and Resolve'; answer='<strong>Why upgrade to an AI chatbot?</strong> Modern bots answer from your knowledge base with citations and hand off to humans when needed-improving CSAT and deflection.'; h2='Chatbots grounded in your brand and knowledge'; b1='Conversation design and intent mapping'; b2='Knowledge base and RAG integration'; b3='Handoff to live agents when needed'; b4='Analytics on resolution and satisfaction'; focus='Support, sales, and internal knowledge chatbots.'; cap1t='Branded experience'; cap1p='Widgets and embedded UIs on web and app.'; cap2t='Knowledge RAG'; cap2p='Accurate answers from approved content.'; cap3t='Integrations'; cap3p='CRM, ticketing, and live-agent handoff.'; faq1q='Can the bot cite sources?'; faq1a='Yes-RAG responses can include links and snippets from your knowledge base.'; faq2q='Will it work with Zendesk or Salesforce?'; faq2a='We integrate with common CS platforms and custom ticketing systems.'; ctat='Ready to launch an AI chatbot?'; ctap='Share your channels and knowledge sources-we will map a rollout plan.'; tags=@('AI chatbots','Knowledge RAG','Canada and USA','CS integrations') },
  @{ slug='ai-automation-solutions'; title='AI Automation Solutions'; short='AI Automation'; meta='AI automation solutions in Canada. Intelligent workflow automation and process AI by Acesoft.'; intro='Combine traditional automation with AI to classify documents, extract data, route requests, and trigger actions across your operations.'; h1='AI <em>Automation Solutions</em><br>Across Your Operations'; answer='<strong>How is AI automation different from RPA?</strong> AI handles unstructured data and judgment tasks; RPA handles rules. We combine both for end-to-end workflows.'; h2='Intelligent automation with measurable ROI'; b1='Process mapping and automation ROI analysis'; b2='Document and email intelligence'; b3='Integration with existing BPM tools'; b4='Measurable time and cost savings'; focus='Document, email, and request automation with AI.'; cap1t='Process discovery'; cap1p='Map ROI and prioritize automation candidates.'; cap2t='AI plus rules'; cap2p='Classification, extraction, and routing.'; cap3t='Dashboards'; cap3p='Exceptions, SLAs, and savings tracking.'; faq1q='Which processes are good candidates?'; faq1a='High-volume document, email, and ticket workflows often see fast wins.'; faq2q='Do you integrate with Power Automate or UiPath?'; faq2a='Yes-we connect to BPM and RPA tools you already use.'; ctat='Ready to automate with AI?'; ctap='Walk us through a repetitive process-we will estimate impact and approach.'; tags=@('AI automation','Document AI','Canada and USA','BPM integration') },
  @{ slug='machine-learning-development'; title='Machine Learning Development'; short='Machine Learning'; meta='Machine learning development services Canada. Custom ML models, pipelines, and MLOps by Acesoft.'; intro='From feature engineering to model deployment, we deliver machine learning that performs in production with reproducible training and drift monitoring.'; h1='Machine <em>Learning Development</em><br>Built for Production'; answer='<strong>When do you need custom ML vs off-the-shelf?</strong> Custom ML wins when your data, metrics, and constraints are unique-we build models and pipelines you can operate.'; h2='ML models and pipelines that perform in the real world'; b1='Problem framing and baseline models'; b2='Feature stores and training pipelines'; b3='Model validation and bias review'; b4='Deployment to cloud or on-prem'; focus='Predictive analytics, forecasting, and classification at scale.'; cap1t='Model development'; cap1p='Training, validation, and model cards.'; cap2t='Pipelines'; cap2p='Reproducible training and inference.'; cap3t='MLOps'; cap3p='Monitoring, drift detection, retraining.'; faq1q='Cloud or on-prem deployment?'; faq1a='Both-we align with your security and data residency requirements.'; faq2q='How do you handle model drift?'; faq2a='Monitoring, alerts, and retraining workflows are part of every production plan.'; ctat='Ready to build ML systems?'; ctap='Share your prediction problem and data-we will propose a modeling path.'; tags=@('Machine learning','MLOps','Canada and USA','Forecasting') },
  @{ slug='ai-saas-product-development'; title='AI SaaS Product Development'; short='AI SaaS'; meta='AI SaaS product development Canada. Build and launch AI-powered SaaS platforms with Acesoft.'; intro='We partner with founders and product teams to ship AI SaaS from MVP through scale including subscription flows, tenant isolation, and AI feature roadmaps.'; h1='AI <em>SaaS Product Development</em><br>From MVP to Scale'; answer='<strong>How do you build AI-native SaaS?</strong> Multi-tenant architecture, metering, and AI backends designed together-so you can launch fast and scale safely.'; h2='AI SaaS products with tenant isolation and growth paths'; b1='Product strategy and technical architecture'; b2='Multi-tenant security and data isolation'; b3='AI feature roadmap prioritization'; b4='DevOps and release automation'; focus='Founders and product teams shipping AI-powered SaaS.'; cap1t='MVP or v1'; cap1p='Ship core AI value with solid foundations.'; cap2t='Multi-tenant SaaS'; cap2p='Auth, billing, and tenant isolation.'; cap3t='AI platform'; cap3p='Usage metering and model ops.'; faq1q='Can you help after launch?'; faq1a='Yes-iteration, scale-up, and feature expansion are common engagements.'; faq2q='Do you work with early-stage startups?'; faq2a='We often start with a focused MVP and a path to production.'; ctat='Ready to build AI SaaS?'; ctap='Share your product vision-we will outline architecture and milestones.'; tags=@('AI SaaS','Multi-tenant','Canada and USA','Founders') },
  @{ slug='enterprise-ai-development'; title='Enterprise AI Development'; short='Enterprise AI'; meta='Enterprise AI development Canada. Secure, compliant AI systems for large organizations by Acesoft.'; intro='Enterprise AI requires governance, SSO, audit logs, and alignment with IT standards. We deliver AI that security and legal teams can stand behind.'; h1='Enterprise <em>AI Development</em><br>With Security and Governance'; answer='<strong>What does enterprise AI require?</strong> SSO, VPC, audit trails, and policy alignment-not just models. We build for security, legal, and IT from day one.'; h2='Governed AI programs for large organizations'; b1='Alignment with ISO 27001 and HIPAA practices'; b2='Private cloud and VPC deployment options'; b3='Role-based access and audit trails'; b4='Stakeholder workshops and rollout planning'; focus='Regulated industries and IT-governed rollouts.'; cap1t='Reference architecture'; cap1p='Security, networking, and integration patterns.'; cap2t='Pilot to production'; cap2p='Phased rollout with stakeholder sign-off.'; cap3t='Enablement'; cap3p='Training and runbooks for internal teams.'; faq1q='Do you support private cloud?'; faq1a='Yes-VPC, on-prem, and hybrid patterns are common for enterprise clients.'; faq2q='How do you work with InfoSec?'; faq2a='We provide architecture reviews, threat modeling, and assessment artifacts early.'; ctat='Ready for enterprise AI?'; ctap='Connect us with your stakeholders-we will align on governance and delivery.'; tags=@('Enterprise AI','ISO and HIPAA','Canada and USA','VPC deploy') },
  @{ slug='ai-integration-services'; title='AI Integration Services'; short='AI Integration'; meta='AI integration services Canada. Integrate LLMs and ML into your existing software stack with Acesoft.'; intro='We embed AI into the tools your teams already use, reducing friction and accelerating adoption without replacing core systems.'; h1='AI <em>Integration Services</em><br>Into Your Stack'; answer='<strong>Why AI integration instead of rip-and-replace?</strong> Embedding AI in CRM, ERP, and custom apps drives adoption faster than standalone tools.'; h2='AI embedded where your teams already work'; b1='API design and middleware layers'; b2='Real-time and batch integration patterns'; b3='Legacy system adapters'; b4='Performance and reliability testing'; focus='Salesforce, Microsoft 365, and custom application integration.'; cap1t='Embedded features'; cap1p='AI inside your existing UIs and flows.'; cap2t='APIs and SDKs'; cap2p='Documented interfaces for your teams.'; cap3t='Quality'; cap3p='Integration tests and operational runbooks.'; faq1q='Can you integrate with legacy systems?'; faq1a='Yes-adapters, middleware, and batch patterns for older stacks.'; faq2q='How do you avoid breaking production?'; faq2a='Staging environments, feature flags, and phased rollouts are standard.'; ctat='Ready to integrate AI?'; ctap='List your target systems-we will propose integration architecture.'; tags=@('AI integration','APIs','Canada and USA','Legacy systems') },
  @{ slug='ai-mvp-development'; title='AI MVP Development'; short='AI MVP'; meta='AI MVP development Canada. Rapid AI prototypes and minimum viable products by Acesoft.'; intro='Validate AI hypotheses quickly with a focused MVP, real users, real data, and clear success metrics so you invest confidently in scale-up.'; h1='AI <em>MVP Development</em><br>Validate Fast'; answer='<strong>Why build an AI MVP first?</strong> An MVP proves value with real users before you commit to full platform spend-we scope tightly and measure outcomes.'; h2='Rapid AI pilots with clear success metrics'; b1='Focused delivery sprints'; b2='Scope control and demo-ready outcomes'; b3='User feedback loops built in'; b4='Clear path from MVP to production'; focus='Founders and innovation teams testing AI ideas.'; cap1t='Working MVP'; cap1p='Demo-ready with real data paths.'; cap2t='Learnings report'; cap2p='Metrics, risks, and scale-up options.'; cap3t='Roadmap'; cap3p='Path to production if the pilot succeeds.'; faq1q='How fast can an MVP ship?'; faq1a='Many MVPs launch in 6-10 weeks depending on data and integrations.'; faq2q='What happens after the MVP?'; faq2a='We can hand off, co-build v1, or run a scale-up program with you.'; ctat='Ready to validate your AI idea?'; ctap='Share your hypothesis-we will propose a lean MVP scope.'; tags=@('AI MVP','Rapid pilot','Canada and USA','Innovation') },
  @{ slug='ai-app-development'; title='AI App Development'; short='AI Apps'; meta='AI app development company Canada. Mobile and web AI applications by Acesoft.'; intro='We build consumer and B2B applications where AI is core to the experience on iOS, Android, and web with performance and privacy considered from day one.'; h1='AI <em>App Development</em><br>Mobile and Web'; answer='<strong>How do you build AI into apps?</strong> We balance on-device vs cloud AI, privacy labels, and UX so AI feels native-not bolted on.'; h2='AI-native apps for iOS, Android, and web'; b1='Cross-platform and native options'; b2='On-device vs cloud AI tradeoff analysis'; b3='App store compliance and privacy labels'; b4='Analytics and feature flagging'; focus='Consumer and B2B apps with AI at the core.'; cap1t='App delivery'; cap1p='Staging or store-ready builds.'; cap2t='AI features'; cap2p='Embedded models and cloud backends.'; cap3t='Ops'; cap3p='Monitoring, crashes, and release cadence.'; faq1q='Flutter, React Native, or native?'; faq1a='We choose based on performance, team skills, and AI requirements.'; faq2q='Can AI run on-device?'; faq2a='When latency or privacy demands it-we evaluate on-device vs cloud per feature.'; ctat='Ready to build an AI app?'; ctap='Share your platform and AI features-we will outline build options.'; tags=@('AI apps','iOS and Android','Canada and USA','On-device AI') }
)

function New-FaqItem([string]$q, [string]$a) {
  return "<div class=`"faq-item`"><h4>$q</h4><p>$a</p></div>"
}

foreach ($p in $pages) {
  $html = $base
  $html = $html.Replace('custom-ai-development-services', $p.slug)
  $html = $html.Replace('Custom AI Development Services', $p.title)
  $html = $html.Replace('Custom AI development services in Canada. Acesoft builds secure, scalable AI systems for enterprises and startups.', $p.meta)
  $html = Set-Marker $html 'EYEBROW' ($p.short + ' | AI Developers.ca | Acesoft Inc')
  $html = Set-Marker $html 'H1' $p.h1
  $html = Set-Marker $html 'INTRO' $p.intro
  $html = Set-Marker $html 'ANSWER' $p.answer
  $html = $html.Replace('Custom AI solutions for enterprise and growth-stage teams', $p.h2)
  $html = $html.Replace('Use-case discovery and ROI-focused roadmap.', ($p.b1 + '.'))
  $html = $html.Replace('Secure architecture with governance and access controls.', ($p.b2 + '.'))
  $html = $html.Replace('Integration with CRM, ERP, and internal tools.', ($p.b3 + '.'))
  $html = $html.Replace('Continuous evaluation and model improvement.', ($p.b4 + '.'))
  $html = Set-Marker $html 'FOCUS' $p.focus
  $html = $html.Replace('<h5>Solution design</h5>', ('<h5>' + $p.cap1t + '</h5>'))
  $html = $html.Replace('Architecture and delivery plans aligned to your stack.', $p.cap1p)
  $html = $html.Replace('<h5>Production build</h5>', ('<h5>' + $p.cap2t + '</h5>'))
  $html = $html.Replace('AI modules, APIs, and integrations ready to ship.', $p.cap2p)
  $html = $html.Replace('<h5>Operate &amp; improve</h5>', ('<h5>' + $p.cap3t + '</h5>'))
  $html = $html.Replace('MLOps, monitoring, and handover for your team.', $p.cap3p)
  $html = Set-Marker $html 'FAQ1' (New-FaqItem $p.faq1q $p.faq1a)
  $html = Set-Marker $html 'FAQ2' (New-FaqItem $p.faq2q $p.faq2a)
  $html = Set-Marker $html 'CTAT' $p.ctat
  $html = Set-Marker $html 'CTAP' $p.ctap
  $html = $html.Replace('Custom AI development', ($p.short + ' development'))
  $tagHtml = ($p.tags | ForEach-Object { "<span class=`"hero-tag`">$_</span>" }) -join "`n          "
  $html = $html.Replace('<span class="hero-tag">Custom AI</span>
          <span class="hero-tag">Enterprise ready</span>
          <span class="hero-tag">Canada &amp; USA</span>
          <span class="hero-tag">Secure delivery</span>', $tagHtml)
  $out = Join-Path $root ($p.slug + '.html')
  [System.IO.File]::WriteAllText($out, $html, $utf8)
  Write-Host "Wrote $out"
}

# Also refresh template page (custom-ai) from base markers unchanged
Write-Host 'Done'
