$root = Split-Path -Parent $PSScriptRoot
$utf8 = New-Object System.Text.UTF8Encoding $false

$industries = @(
  @{ slug='ai-for-healthcare'; title='AI for Healthcare'; icon='fa-heartbeat'; hub='Clinical workflows, patient engagement, and compliant AI for providers and health tech.'; meta='AI for healthcare in Canada. HIPAA-aware clinical AI, documentation automation, and patient engagement by Acesoft.'; intro='Acesoft builds healthcare AI with privacy, clinical safety, and integration into EHR and care pathways-from ambient documentation to triage assistants.'; h1='AI for <em>Healthcare</em><br>Built for Clinical Trust'; answer='<strong>Why AI in healthcare?</strong> Reduce documentation burden, improve triage, and personalize care-while meeting HIPAA and clinical governance requirements.'; h2='Healthcare AI that clinicians and compliance teams can trust'; b1='Ambient clinical documentation and coding support'; b2='Patient intake, triage, and engagement assistants'; b3='FHIR-friendly integration with EHR systems'; b4='Audit trails, access controls, and human review'; focus='Hospitals, clinics, digital health, and medtech product teams.'; cap1t='Clinical assistants'; cap1p='Documentation, scheduling, and patient Q&amp;A with guardrails.'; cap2t='Operational AI'; cap2p='Prior auth, claims, and revenue cycle automation.'; cap3t='Governance'; cap3p='HIPAA-aligned architecture and evaluation.'; faq1q='Do you support HIPAA requirements?'; faq1a='Yes-we design for HIPAA-aligned controls, BAAs, and least-privilege access.'; faq2q='Can you integrate with Epic or Cerner?'; faq2a='We integrate via FHIR, HL7, and vendor APIs depending on your environment.'; ctat='Ready for healthcare AI?'; ctap='Share your clinical use case-we will outline a compliant discovery and pilot plan.'; tags=@('Healthcare AI','HIPAA aware','Clinical workflows','Canada &amp; USA') },
  @{ slug='ai-for-retail'; title='AI for Retail'; icon='fa-shopping-cart'; hub='Demand forecasting, personalization, and store operations AI for modern retail.'; meta='AI for retail in Canada. Personalization, demand forecasting, and store ops AI by Acesoft.'; intro='Retail AI that lifts conversion and margins-personalized recommendations, inventory intelligence, and associate copilots connected to your commerce stack.'; h1='AI for <em>Retail</em><br>Personalize and Optimize'; answer='<strong>How does AI help retail?</strong> Better forecasts, tailored experiences, and faster operations across e-commerce and brick-and-mortar.'; h2='Retail AI from shelf to checkout'; b1='Personalization and recommendation engines'; b2='Demand forecasting and assortment planning'; b3='Visual search and catalog enrichment'; b4='Associate copilots for stores and contact centers'; focus='Retailers, DTC brands, and commerce platforms.'; cap1t='Shopper experience'; cap1p='Recommendations, search, and dynamic merchandising.'; cap2t='Supply chain'; cap2p='Forecasting, allocation, and shrink insights.'; cap3t='Operations'; cap3p='Staff scheduling and in-store assistants.'; faq1q='Can you connect to Shopify or Salesforce Commerce?'; faq1a='Yes-common commerce, CRM, and POS platforms are supported.'; faq2q='How fast can we see ROI?'; faq2a='Many pilots focus on one journey-personalization or forecasting-with KPIs in 8-12 weeks.'; ctat='Ready for retail AI?'; ctap='Tell us your channels and data-we will propose a focused retail AI roadmap.'; tags=@('Retail AI','Personalization','Forecasting','Omnichannel') },
  @{ slug='ai-for-finance'; title='AI for Finance'; icon='fa-bank'; hub='Fraud detection, KYC automation, and intelligent finance operations.'; meta='AI for finance and banking in Canada. Fraud, risk, and ops automation with governance by Acesoft.'; intro='Financial services AI with strong controls-fraud and AML signals, document intelligence, and customer service copilots designed for regulated environments.'; h1='AI for <em>Finance</em><br>Secure and Governed'; answer='<strong>Why AI in finance?</strong> Detect risk faster, automate document-heavy workflows, and improve client service-with auditability and model governance.'; h2='Finance AI built for risk and compliance'; b1='Fraud and anomaly detection pipelines'; b2='KYC, onboarding, and document extraction'; b3='Wealth and banking service copilots'; b4='Model risk management and explainability'; focus='Banks, credit unions, fintech, and insurance partners.'; cap1t='Risk &amp; fraud'; cap1p='Real-time scoring and case prioritization.'; cap2t='Operations'; cap2p='Loan processing, statements, and reconciliation.'; cap3t='Client experience'; cap3p='Secure advisors and support automation.'; faq1q='Do you support SOC 2 and audit requirements?'; faq1a='Yes-governance, logging, and model documentation are part of delivery.'; faq2q='Can models be explainable?'; faq2a='We provide explainability artifacts where regulators or risk teams require them.'; ctat='Ready for finance AI?'; ctap='Describe your regulatory context and use cases-we will align on a governed approach.'; tags=@('Finance AI','Fraud detection','KYC automation','Governance') },
  @{ slug='ai-for-logistics'; title='AI for Logistics'; icon='fa-truck'; hub='Route optimization, warehouse intelligence, and supply chain visibility.'; meta='AI for logistics and supply chain in Canada. Routing, warehouse, and visibility solutions by Acesoft.'; intro='Logistics AI for fleets, warehouses, and planners-route optimization, demand sensing, and exception management integrated with TMS and WMS.'; h1='AI for <em>Logistics</em><br>Move Smarter'; answer='<strong>How does AI improve logistics?</strong> Better routes, fewer delays, and clearer visibility across suppliers, hubs, and last mile.'; h2='Supply chain AI from planning to delivery'; b1='Dynamic routing and load optimization'; b2='Warehouse picking and slotting intelligence'; b3='Demand sensing across nodes'; b4='Exception alerts and ETA prediction'; focus='3PLs, carriers, distributors, and manufacturers.'; cap1t='Planning'; cap1p='Forecasting and network optimization.'; cap2t='Execution'; cap2p='Routing, dispatch, and yard management.'; cap3t='Visibility'; cap3p='Track-and-trace and customer notifications.'; faq1q='Do you integrate with TMS/WMS?'; faq1a='Yes-via APIs and event streams from common logistics platforms.'; faq2q='Can this run at edge or on-prem?'; faq2a='Hybrid deployments are available when latency or data residency requires it.'; ctat='Ready for logistics AI?'; ctap='Share your network and systems-we will map high-impact automation.'; tags=@('Logistics AI','Route optimization','Warehouse AI','Supply chain') },
  @{ slug='ai-for-manufacturing'; title='AI for Manufacturing'; icon='fa-industry'; hub='Predictive maintenance, quality vision, and smart factory analytics.'; meta='AI for manufacturing in Canada. Predictive maintenance, quality inspection, and MES integration by Acesoft.'; intro='Manufacturing AI on the plant floor-predictive maintenance, computer vision quality, and production analytics tied to MES and IoT data.'; h1='AI for <em>Manufacturing</em><br>Smarter Plants'; answer='<strong>Why AI in manufacturing?</strong> Reduce downtime, catch defects earlier, and optimize throughput with data from machines and lines.'; h2='Industrial AI for reliability and quality'; b1='Predictive maintenance and anomaly detection'; b2='Visual inspection and defect classification'; b3='Production scheduling and yield optimization'; b4='Edge deployment on lines and plants'; focus='Discrete and process manufacturers, industrials, and OEMs.'; cap1t='Reliability'; cap1p='Sensor fusion and failure prediction.'; cap2t='Quality'; cap2p='Vision systems and SPC augmentation.'; cap3t='Productivity'; cap3p='OEE dashboards and operator guidance.'; faq1q='Can you work with legacy PLCs and MES?'; faq1a='Yes-adapters and historians bridge OT data to modern AI pipelines.'; faq2q='Edge or cloud?'; faq2a='We design hybrid architectures based on latency and connectivity.'; ctat='Ready for manufacturing AI?'; ctap='Describe your lines and data sources-we will propose a plant-floor pilot.'; tags=@('Manufacturing AI','Predictive maintenance','Quality vision','Smart factory') },
  @{ slug='ai-for-real-estate'; title='AI for Real Estate'; icon='fa-building'; hub='Property insights, valuation support, and agent productivity tools.'; meta='AI for real estate in Canada. Valuation support, search, and agent copilots by Acesoft.'; intro='Real estate AI for brokerages and proptech-valuation support, listing enrichment, lead qualification, and document automation for transactions.'; h1='AI for <em>Real Estate</em><br>Close Deals Faster'; answer='<strong>How does AI help real estate?</strong> Richer listings, faster qualification, and less manual work on contracts and disclosures.'; h2='Proptech AI for agents and platforms'; b1='Valuation and comp analysis assistants'; b2='Natural-language property search'; b3='Lead scoring and nurture automation'; b4='Lease and purchase document intelligence'; focus='Brokerages, MLS platforms, and property managers.'; cap1t='Discovery'; cap1p='Search, maps, and recommendation UX.'; cap2t='Transactions'; cap2p='Document extraction and checklist automation.'; cap3t='Operations'; cap3p='Tenant service and maintenance routing.'; faq1q='Can you use our MLS feed?'; faq1a='Yes-with proper licensing and secure ingestion pipelines.'; faq2q='White-label for our brand?'; faq2a='Embeddable widgets and APIs support branded experiences.'; ctat='Ready for real estate AI?'; ctap='Share your platform or brokerage goals-we will scope a practical rollout.'; tags=@('Real estate AI','Proptech','Valuation support','Agent tools') },
  @{ slug='ai-for-ecommerce'; title='AI for Ecommerce'; icon='fa-shopping-bag'; hub='Conversion optimization, search, and post-purchase automation for online stores.'; meta='AI for ecommerce in Canada. Search, recommendations, and support automation by Acesoft.'; intro='Ecommerce AI that grows revenue-smarter search, bundles, churn prevention, and support bots integrated with your storefront and CDP.'; h1='AI for <em>Ecommerce</em><br>Grow Online Revenue'; answer='<strong>Why AI for ecommerce?</strong> Shoppers find products faster, support scales, and marketing gets more relevant-with measurable lift to AOV and retention.'; h2='Commerce AI across the buyer journey'; b1='Semantic search and merchandising rules'; b2='Recommendations and dynamic pricing tests'; b3='Cart recovery and lifecycle messaging'; b4='Returns and support automation'; focus='DTC brands, marketplaces, and B2B commerce.'; cap1t='Merchandising'; cap1p='Search, ranking, and catalog AI.'; cap2t='Marketing'; cap2p='Segments, offers, and content generation.'; cap3t='Service'; cap3p='Chat, returns, and order status bots.'; faq1q='Shopify, Magento, or custom?'; faq1a='All are supported via APIs, webhooks, and event streams.'; faq2q='How do you measure success?'; faq2a='We define KPIs-conversion, AOV, CSAT-before build and track in production.'; ctat='Ready for ecommerce AI?'; ctap='Share your stack and goals-we will prioritize quick-win use cases.'; tags=@('Ecommerce AI','Site search','Recommendations','Support bots') },
  @{ slug='ai-for-media-content'; title='AI for Media & Content'; icon='fa-film'; hub='Content workflows, metadata, and audience intelligence for publishers and studios.'; meta='AI for media and content companies in Canada. Metadata, localization, and audience AI by Acesoft.'; intro='Media AI for production and distribution-automated metadata, localization, clip discovery, and audience insights with rights-aware guardrails.'; h1='AI for <em>Media &amp; Content</em><br>Create and Distribute Smarter'; answer='<strong>How does AI help media teams?</strong> Faster cataloging, localized assets, and data-driven programming without losing creative control.'; h2='Content AI with rights and brand safety'; b1='Metadata tagging and semantic search'; b2='Localization and subtitle workflows'; b3='Highlight detection and clip generation'; b4='Audience segmentation and recommendations'; focus='Broadcasters, streamers, publishers, and studios.'; cap1t='Production'; cap1p='Ingest, tag, and repurpose assets.'; cap2t='Distribution'; cap2p='Personalized feeds and programming support.'; cap3t='Monetization'; cap3p='Ad targeting and sponsorship insights.'; faq1q='How do you handle copyrighted material?'; faq1a='Access controls, watermarks, and policy filters are built into workflows.'; faq2q='Human review for published content?'; faq2a='Yes-approval queues are standard for customer-facing outputs.'; ctat='Ready for media AI?'; ctap='Tell us your content types and platforms-we will design a rights-safe pipeline.'; tags=@('Media AI','Metadata automation','Localization','Audience insights') },
  @{ slug='ai-for-asset-management'; title='AI for Asset Management'; icon='fa-pie-chart'; hub='Portfolio analytics, research automation, and client reporting for asset managers.'; meta='AI for asset management in Canada. Research automation, risk analytics, and client reporting by Acesoft.'; intro='Asset management AI for research, risk, and client teams-document intelligence on filings, portfolio commentary drafts, and compliance-friendly workflows.'; h1='AI for <em>Asset Management</em><br>Research at Scale'; answer='<strong>Why AI for asset managers?</strong> Analysts spend less time on documents and more on insight-with controls suitable for regulated investment firms.'; h2='Investment AI with compliance in mind'; b1='Research summarization on filings and news'; b2='Risk factor tagging and scenario support'; b3='Client reporting and Q&amp;A assistants'; b4='Audit logs and approval workflows'; focus='Asset managers, wealth platforms, and fund administrators.'; cap1t='Research'; cap1p='Summaries, extraction, and watchlists.'; cap2t='Risk'; cap2p='Signals, stress views, and alerts.'; cap3t='Client service'; cap3p='Secure portals and commentary support.'; faq1q='Can outputs be restricted to approved sources?'; faq1a='Yes-RAG and allowlists keep models grounded in your research library.'; faq2q='Do you support SOC controls?'; faq2a='Security and logging patterns align with institutional requirements.'; ctat='Ready for asset management AI?'; ctap='Share your research and compliance needs-we will propose a governed pilot.'; tags=@('Asset management AI','Research automation','Risk analytics','Compliance') },
  @{ slug='ai-for-education'; title='AI for Education'; icon='fa-graduation-cap'; hub='Learning personalization, grading support, and campus operations for schools and edtech.'; meta='AI for education in Canada. Personalized learning, tutoring, and campus ops by Acesoft.'; intro='Education AI for institutions and edtech-adaptive learning paths, instructor copilots, and administrative automation with student privacy in focus.'; h1='AI for <em>Education</em><br>Personalize Learning'; answer='<strong>How can AI support education?</strong> Tutoring at scale, less admin burden, and insights for educators-while protecting student data.'; h2='Edtech AI for learners and administrators'; b1='Adaptive practice and tutoring assistants'; b2='Grading support and rubric alignment'; b3='Enrollment and advising chatbots'; b4='FERPA-aware data handling'; focus='K-12, higher ed, corporate L&amp;D, and edtech vendors.'; cap1t='Learning'; cap1p='Tutors, assessments, and content recommendations.'; cap2t='Faculty'; cap2p='Lesson planning and feedback tools.'; cap3t='Operations'; cap3p='Scheduling, FAQ, and document routing.'; faq1q='Do you comply with student privacy rules?'; faq1a='We design for FERPA-aligned practices and regional privacy requirements.'; faq2q='Can teachers override AI suggestions?'; faq2a='Human-in-the-loop is default for instructional decisions.'; ctat='Ready for education AI?'; ctap='Describe your learners and platforms-we will outline a responsible rollout.'; tags=@('Education AI','Adaptive learning','Edtech','Student privacy') },
  @{ slug='ai-for-insurance'; title='AI for Insurance'; icon='fa-shield'; hub='Claims automation, underwriting support, and policy service for insurers.'; meta='AI for insurance in Canada. Claims, underwriting, and policy service automation by Acesoft.'; intro='Insurance AI for carriers and MGAs-claims triage, FNOL bots, underwriting document intelligence, and fraud signals with explainable outputs.'; h1='AI for <em>Insurance</em><br>Faster Claims and Underwriting'; answer='<strong>Why AI in insurance?</strong> Speed up claims and quotes, reduce leakage, and improve policyholder experience with governed models.'; h2='Insurance AI from FNOL to renewal'; b1='Claims document extraction and routing'; b2='Underwriting risk summarization'; b3='Policyholder self-service assistants'; b4='Fraud and subrogation signals'; focus='P&amp;C, life, health insurers, and insurtech.'; cap1t='Claims'; cap1p='Triage, estimates, and comms automation.'; cap2t='Underwriting'; cap2p='Risk factors from applications and docs.'; cap3t='Service'; cap3p='Policy Q&amp;A and renewal nudges.'; faq1q='Can you integrate with Guidewire or Duck Creek?'; faq1a='Yes-via APIs and integration layers common in insurance stacks.'; faq2q='Explainability for underwriting?'; faq2a='We document features and provide reason codes where required.'; ctat='Ready for insurance AI?'; ctap='Share your lines of business and systems-we will prioritize high-ROI workflows.'; tags=@('Insurance AI','Claims automation','Underwriting','Insurtech') },
  @{ slug='ai-for-legal'; title='AI for Legal'; icon='fa-gavel'; hub='Contract review, discovery support, and legal research assistants for firms and legal ops.'; meta='AI for legal teams in Canada. Contract review, discovery, and research assistants by Acesoft.'; intro='Legal AI for law firms and corporate legal-contract playbooks, clause extraction, discovery prioritization, and research copilots with confidentiality controls.'; h1='AI for <em>Legal</em><br>Accelerate Legal Work'; answer='<strong>How does AI help legal teams?</strong> Faster review cycles and better search across matters-with permissions and audit trails firms require.'; h2='Legal AI with confidentiality and control'; b1='Contract review against playbooks'; b2='Matter and discovery document prioritization'; b3='Research assistants with citations'; b4='Client-matter access boundaries'; focus='Law firms, corporate legal, and ALSPs.'; cap1t='Contracts'; cap1p='Review, redline support, and obligation tracking.'; cap2t='Litigation'; cap2p='Discovery ranking and chronology aids.'; cap3t='Knowledge'; cap3p='Secure search across precedents and policies.'; faq1q='Is client data isolated?'; faq1a='Yes-matter-level isolation and no training on your data without agreement.'; faq2q='Do attorneys stay in control?'; faq2a='AI drafts and flags; attorneys approve outcomes.'; ctat='Ready for legal AI?'; ctap='Tell us your practice areas and DMS-we will scope a secure pilot.'; tags=@('Legal AI','Contract review','Discovery','Confidentiality') },
  @{ slug='ai-for-government'; title='AI for Government & Public Sector'; icon='fa-landmark'; hub='Citizen services, document processing, and policy analytics for public agencies.'; meta='AI for government and public sector in Canada. Citizen services and document AI by Acesoft.'; intro='Public sector AI with accessibility and transparency-citizen service bots, forms automation, and analytics with security classifications in mind.'; h1='AI for <em>Government</em><br>Better Citizen Services'; answer='<strong>How can government use AI responsibly?</strong> Faster services and less backlog-with bilingual support, auditability, and procurement-friendly delivery.'; h2='Public-sector AI with accountability'; b1='Citizen FAQ and application assistants'; b2='Document classification and routing'; b3='Policy research and summarization aids'; b4='Security and access tiering'; focus='Federal, provincial, municipal, and crown agencies.'; cap1t='Citizen experience'; cap1p='24/7 service and form help.'; cap2t='Operations'; cap2p='Back-office automation and queues.'; cap3t='Transparency'; cap3p='Logging, bilingual UX, and human escalation.'; faq1q='Do you support English and French?'; faq1a='Yes-bilingual experiences are standard for Canadian public sector work.'; faq2q='Cloud or on-prem?'; faq2a='We align with GC cloud guidance and agency hosting requirements.'; ctat='Ready for public-sector AI?'; ctap='Describe your program and security tier-we will propose a compliant path.'; tags=@('Government AI','Public sector','Citizen services','Bilingual') },
  @{ slug='ai-for-hospitality-travel'; title='AI for Hospitality & Travel'; icon='fa-plane'; hub='Guest experience, revenue management, and operations for hotels and travel brands.'; meta='AI for hospitality and travel in Canada. Guest experience and revenue AI by Acesoft.'; intro='Hospitality AI for hotels, airlines, and OTAs-concierge bots, dynamic packaging support, reviews analysis, and staff scheduling assistance.'; h1='AI for <em>Hospitality &amp; Travel</em><br>Delight Guests and Optimize Yield'; answer='<strong>Why AI in travel and hospitality?</strong> Personalized stays, smarter pricing, and operations that scale through peak seasons.'; h2='Guest-first AI across the journey'; b1='Concierge and booking assistants'; b2='Review and sentiment insights'; b3='Revenue management decision support'; b4='Housekeeping and staffing optimization'; focus='Hotels, resorts, airlines, and travel platforms.'; cap1t='Guest UX'; cap1p='Messaging, upsell, and itinerary help.'; cap2t='Revenue'; cap2p='Forecasting and rate recommendations.'; cap3t='Operations'; cap3p='Staffing, maintenance, and inventory.'; faq1q='PMS and CRS integrations?'; faq1a='We connect to common hospitality and GDS systems via APIs.'; faq2q='Multilingual guests?'; faq2a='Assistants can support multiple languages for international travelers.'; ctat='Ready for hospitality AI?'; ctap='Share your properties or routes-we will identify high-impact guest and ops wins.'; tags=@('Hospitality AI','Travel','Guest experience','Revenue') },
  @{ slug='ai-for-agriculture'; title='AI for Agriculture'; icon='fa-leaf'; hub='Crop intelligence, supply planning, and field operations for agribusiness.'; meta='AI for agriculture in Canada. Crop intelligence, supply planning, and ag ops by Acesoft.'; intro='Agriculture AI for growers and agribusiness-yield prediction, pest and disease vision, supply planning, and traceability from field to market.'; h1='AI for <em>Agriculture</em><br>From Field to Market'; answer='<strong>How does AI help agriculture?</strong> Better decisions on inputs, timing, and logistics using imagery, weather, and IoT sensor data.'; h2='Agtech AI for sustainable productivity'; b1='Crop health vision and scouting aids'; b2='Yield and price forecasting'; b3='Supply chain and traceability analytics'; b4='Equipment and irrigation optimization'; focus='Growers, co-ops, ag retailers, and food processors.'; cap1t='Field intelligence'; cap1p='Imagery, sensors, and models per crop.'; cap2t='Planning'; cap2p='Planting, input, and logistics planning.'; cap3t='Traceability'; cap3p='Batch tracking and quality documentation.'; faq1q='Satellite and drone imagery?'; faq1a='Yes-we ingest aerial and satellite feeds where available.'; faq2q='Rural connectivity constraints?'; faq2a='Edge and offline-first patterns are considered for low-connectivity sites.'; ctat='Ready for agriculture AI?'; ctap='Tell us your crops and data sources-we will scope a practical field pilot.'; tags=@('Agriculture AI','Agtech','Crop intelligence','Supply chain') },
  @{ slug='ai-for-telecommunications'; title='AI for Telecommunications'; icon='fa-signal'; hub='Network ops, customer care, and churn prevention for telecom providers.'; meta='AI for telecommunications in Canada. Network analytics, care automation, and churn AI by Acesoft.'; intro='Telecom AI for carriers and ISPs-network fault prediction, care copilots, churn models, and sales guidance integrated with BSS/OSS.'; h1='AI for <em>Telecommunications</em><br>Networks and Care at Scale'; answer='<strong>Why AI for telecom?</strong> Reduce downtime, resolve tickets faster, and retain subscribers with predictive and generative capabilities.'; h2='Telecom AI across network and customer layers'; b1='Fault prediction and root-cause hints'; b2='Care and technical support copilots'; b3='Churn and upsell propensity models'; b4='Field dispatch prioritization'; focus='Mobile, fixed, and enterprise telecom providers.'; cap1t='Network'; cap1p='Alarms, topology, and capacity insights.'; cap2t='Care'; cap2p='Agent assist and self-service bots.'; cap3t='Growth'; cap3p='Offers, retention, and sales guidance.'; faq1q='BSS/OSS integration?'; faq1a='We integrate with billing, CRM, and ticketing platforms common in telecom.'; faq2q='Real-time network data?'; faq2a='Streaming pipelines support near-real-time analytics where needed.'; ctat='Ready for telecom AI?'; ctap='Share your stack and KPIs-we will propose network and care priorities.'; tags=@('Telecom AI','Network ops','Customer care','Churn prevention') }
)

function Set-Marker([string]$html, [string]$name, [string]$value) {
  $pattern = "(?s)<!--SVC:$name-->.*?<!--/SVC:$name-->"
  $replacement = "<!--SVC:$name-->$value<!--/SVC:$name-->"
  return [regex]::Replace($html, $pattern, [System.Text.RegularExpressions.MatchEvaluator]{ param($m) $replacement })
}

function Build-IndustryPage($p, [string]$html) {
  $out = $html
  $out = $out.Replace('custom-ai-development-services', $p.slug)
  $out = $out.Replace('Custom AI Development Services', $p.title)
  $out = $out.Replace('Custom AI development services in Canada. Acesoft builds secure, scalable AI systems for enterprises and startups.', $p.meta)
  $out = Set-Marker $out 'EYEBROW' ($p.title + ' | Industries | Acesoft Inc')
  $out = Set-Marker $out 'H1' $p.h1
  $out = Set-Marker $out 'INTRO' $p.intro
  $out = Set-Marker $out 'ANSWER' $p.answer
  $out = $out.Replace('Custom AI solutions for enterprise and growth-stage teams', $p.h2)
  $out = $out.Replace('Use-case discovery and ROI-focused roadmap.', ($p.b1 + '.'))
  $out = $out.Replace('Secure architecture with governance and access controls.', ($p.b2 + '.'))
  $out = $out.Replace('Integration with CRM, ERP, and internal tools.', ($p.b3 + '.'))
  $out = $out.Replace('Continuous evaluation and model improvement.', ($p.b4 + '.'))
  $out = Set-Marker $out 'FOCUS' $p.focus
  $out = $out.Replace('Solution design', $p.cap1t)
  $out = $out.Replace('Architecture and delivery plans aligned to your stack.', $p.cap1p)
  $out = $out.Replace('Production build', $p.cap2t)
  $out = $out.Replace('AI modules, APIs, and integrations ready to ship.', $p.cap2p)
  $out = $out.Replace('Operate &amp; improve', $p.cap3t)
  $out = $out.Replace('MLOps, monitoring, and handover for your team.', $p.cap3p)
  $faq1 = "<motion class=`"faq-item`"><h4>$($p.faq1q)</h4><p>$($p.faq1a)</p></div>"
  $faq1 = "<div class=`"faq-item`"><h4>$($p.faq1q)</h4><p>$($p.faq1a)</p></motion>"
  $faq1 = "<div class=`"faq-item`"><h4>$($p.faq1q)</h4><p>$($p.faq1a)</p></div>"
  $faq2 = "<div class=`"faq-item`"><h4>$($p.faq2q)</h4><p>$($p.faq2a)</p></div>"
  $out = Set-Marker $out 'FAQ1' $faq1
  $out = Set-Marker $out 'FAQ2' $faq2
  $out = Set-Marker $out 'CTAT' $p.ctat
  $out = Set-Marker $out 'CTAP' $p.ctap
  $out = $out.Replace('Custom AI development', ($p.title -replace '^AI for ','') + ' AI')
  $out = $out.Replace('<motion class="silo-label">More AI services</div>', '<div class="silo-label">More industries</motion>')
  $out = $out.Replace('<div class="silo-label">More AI services</div>', '<div class="silo-label">More industries</div>')
  $silo = @"
            <a href="ai-industries.html">All industries</a>
            <a href="ai-for-finance.html">Finance</a>
            <a href="ai-for-retail.html">Retail</a>
            <a href="ai-for-healthcare.html">Healthcare</a>
            <a href="ai-development-services.html">AI development services</a>
"@
  $out = [regex]::Replace($out, '(?s)<div class="silo-links">.*?</motion>', "<div class=`"silo-links`">`n$silo`n          </div>", 1)
  $out = [regex]::Replace($out, '(?s)<div class="silo-links">.*?</motion>', "<div class=`"silo-links`">`n$silo`n          </div>", 1)
  $out = [regex]::Replace($out, '(?s)<div class="silo-links">.*?</div>', "<motion class=`"silo-links`">`n$silo`n          </div>", 1)
  $out = [regex]::Replace($out, '(?s)<div class="silo-links">.*?</motion>', "<div class=`"silo-links`">`n$silo`n          </div>", 1)
  $out = [regex]::Replace($out, '(?s)<div class="silo-links">[\s\S]*?</div>', "<div class=`"silo-links`">`n$silo`n          </motion>", 1)
  $out = [regex]::Replace($out, '(?s)<div class="silo-links">[\s\S]*?</div>', "<div class=`"silo-links`">`n$silo`n          </div>", 1)
  $tagsHtml = ($p.tags | ForEach-Object { "<span class=`"hero-tag`">$_</span>" }) -join "`n          "
  $out = [regex]::Replace($out, '(?s)<div class="hero-tags">.*?</div>', "<div class=`"hero-tags`">`n          $tagsHtml`n        </div>", 1)
  $out = $out.Replace('<li><a href="ai-development-services.html" class="acesoft-nav-current-link">AI Development</a></li>', '<li><a href="ai-development-services.html">AI Development</a></li>')
  $out = $out.Replace('<li><a href="ai-staffing.html">AI Staffing</a></li>', '<li><a href="ai-staffing.html">AI Staffing</a></li>' + "`n								<li><a href=`"ai-industries.html`" class=`"acesoft-nav-current-link`">Industries</a></li>")
  $out = $out.Replace('generative-ai-development.html">Generative AI', 'ai-for-healthcare.html">Healthcare')
  $out = $out.Replace('llm-development.html">LLM Development', 'ai-for-finance.html">Finance')
  $out = $out.Replace('ai-agent-development.html">AI Agents', 'ai-for-retail.html">Retail')
  $out = $out.Replace('machine-learning-development.html">Machine Learning', 'ai-for-logistics.html">Logistics')
  return $out
}

# Hub page
$hubCards = ($industries | ForEach-Object {
  "            <a href=`"$($_.slug).html`" class=`"seo-service-card`"><span class=`"seo-service-card-icon`"><i class=`"fa $($_.icon)`"></i></span><h4>$($_.title)</h4><p>$($_.hub)</p><span class=`"seo-service-card-link`">View industry</span></a>"
}) -join "`n"

$hubSrc = Join-Path $root 'ai-staffing.html'
$hub = [System.IO.File]::ReadAllText($hubSrc, $utf8)
$hub = $hub.Replace('ai-staffing.html', 'ai-industries.html')
$hub = $hub.Replace('AI Staffing Services | Hire AI Engineers & ML Experts | Acesoft', 'AI Solutions by Industry | Sector-Specific AI | Acesoft')
$hub = $hub.Replace('Scale your team with Acesoft AI staffing services. Hire vetted AI engineers, ML specialists, data scientists, and MLOps experts for flexible delivery.', 'Industry-specific AI solutions for healthcare, finance, retail, logistics, and more. Acesoft builds secure, production-ready AI for your sector in Canada and the USA.')
$hub = $hub.Replace('og:title" content="AI Development Company Canada & USA | Custom AI Solutions"', 'og:title" content="AI Solutions by Industry | Acesoft Canada"')
$hub = $hub.Replace('twitter:title" content="AI Development Company Canada & USA | Custom AI Solutions"', 'twitter:title" content="AI Solutions by Industry | Acesoft Canada"')
$hub = $hub.Replace('AI Staffing Services', 'AI Solutions by Industry')
$hub = $hub.Replace('Hire AI Experts Who<br>', 'Industry-Specific AI<br>')
$hub = $hub.Replace('<em>Deliver Fast &amp; Scale</em>', '<em>Built for Your Sector</em>')
$hub = $hub.Replace('Augment your team with experienced AI engineers, LLM specialists, data scientists, and MLOps professionals who integrate quickly and deliver production-grade outcomes.', 'From healthcare and finance to retail and manufacturing-Acesoft delivers AI that respects your regulations, data, and operating model.')
$hub = $hub.Replace('AI Engineers On Demand', 'Healthcare &amp; Life Sciences')
$hub = $hub.Replace('LLM &amp; RAG Specialists', 'Finance &amp; Insurance')
$hub = $hub.Replace('MLOps &amp; Data Experts', 'Retail &amp; Ecommerce')
$hub = $hub.Replace('Dedicated Pods', 'Logistics &amp; Manufacturing')
$hub = $hub.Replace('Flexible Engagement Models', '16 Industry Playbooks')
$hub = $hub.Replace('id="aiStaffingHub"', 'id="aiIndustriesHub"')
$hub = $hub.Replace('Staffing Options', 'Industries We Serve')
$hub = $hub.Replace('Explore AI Staffing &amp; Hiring Services', 'Explore AI Solutions by Industry')
$hub = $hub.Replace('Flexible ways to add AI engineers and teams-each option has a dedicated page with engagement models and how Acesoft can help.', 'Each industry has a dedicated page with use cases, deliverables, and how Acesoft can help your team in Canada and beyond.')
$hub = $hub.Replace('seo-service-grid seo-service-grid--staffing', 'seo-service-grid seo-service-grid--industries')
$hub = $hub.Replace('<li><a href="ai-industries.html" class="acesoft-nav-current-link">AI Staffing</a></li>', '<li><a href="ai-staffing.html">AI Staffing</a></li>' + "`n								<li><a href=`"ai-industries.html`" class=`"acesoft-nav-current-link`">Industries</a></li>")

$hub = [regex]::Replace($hub, '(?s)(<div class="seo-service-grid seo-service-grid--industries">).*?(</div>\s*</motion>\s*</motion>)', "`$1`n$hubCards`n          </div>", 1)
$hub = [regex]::Replace($hub, '(?s)(<motion class="seo-service-grid seo-service-grid--industries">).*?(</div>)', "`$1`n$hubCards`n          `$2", 1)
$hub = [regex]::Replace($hub, '(?s)<div class="seo-service-grid seo-service-grid--industries">[\s\S]*?</motion>\s*</motion>', "<div class=`"seo-service-grid seo-service-grid--industries`">`n$hubCards`n          </div>", 1)
$hub = [regex]::Replace($hub, '(?s)<div class="seo-service-grid seo-service-grid--industries">[\s\S]*?</div>\s*</div>', "<div class=`"seo-service-grid seo-service-grid--industries`">`n$hubCards`n          </div>", 1)

[System.IO.File]::WriteAllText((Join-Path $root 'ai-industries.html'), $hub, $utf8)
Write-Host 'Created ai-industries.html'

$template = [System.IO.File]::ReadAllText((Join-Path $root 'custom-ai-development-services.html'), $utf8)
foreach ($p in $industries) {
  $page = Build-IndustryPage $p $template
  [System.IO.File]::WriteAllText((Join-Path $root ($p.slug + '.html')), $page, $utf8)
  Write-Host "Created $($p.slug).html"
}

$sitemapPath = Join-Path $root 'sitemap.xml'
$sitemap = [System.IO.File]::ReadAllText($sitemapPath, $utf8)
if ($sitemap -notmatch 'ai-industries.html') {
  $insert = "  <url>`n    <loc>https://www.aidevelopers.ca/ai-industries.html</loc>`n  </url>`n"
  foreach ($p in $industries) {
    $insert += "  <url>`n    <loc>https://www.aidevelopers.ca/$($p.slug).html</loc>`n  </url>`n"
  }
  $sitemap = $sitemap.Replace('</urlset>', ($insert + '</urlset>'))
  [System.IO.File]::WriteAllText($sitemapPath, $sitemap, $utf8)
}
Write-Host 'Done'
