# AI Development Canada / USA hubs + city SEO landing pages
$root = Split-Path -Parent $PSScriptRoot
$utf8 = New-Object System.Text.UTF8Encoding $false

function Set-Marker([string]$html, [string]$name, [string]$value) {
  $pattern = "(?s)<!--SVC:$name-->.*?<!--/SVC:$name-->"
  $replacement = "<!--SVC:$name-->$value<!--/SVC:$name-->"
  return [regex]::Replace($html, $pattern, [System.Text.RegularExpressions.MatchEvaluator]{ param($m) $replacement })
}

function Build-LocationPage($p, [string]$html) {
  $out = $html
  $out = $out.Replace('custom-ai-development-services', $p.slug)
  $out = $out.Replace('Custom AI Development Services', $p.title)
  $out = $out.Replace('Custom AI development services in Canada. Acesoft builds secure, scalable AI systems for enterprises and startups.', $p.meta)
  $out = Set-Marker $out 'EYEBROW' ($p.title + ' | ' + $p.hubLabel + ' | Acesoft')
  $out = Set-Marker $out 'H1' $p.h1
  $out = Set-Marker $out 'INTRO' $p.intro
  $out = Set-Marker $out 'ANSWER' $p.answer
  $out = $out.Replace('Custom AI solutions for enterprise and growth-stage teams', $p.h2)
  $out = $out.Replace('Use-case discovery and ROI-focused roadmap.', ($p.b1 + '.'))
  $out = $out.Replace('Secure architecture with governance and access controls.', ($p.b2 + '.'))
  $out = $out.Replace('Integration with CRM, ERP, and internal tools.', ($p.b3 + '.'))
  $out = $out.Replace('Continuous evaluation and model improvement.', ($p.b4 + '.'))
  $out = Set-Marker $out 'FOCUS' $p.focus
  $out = $out.Replace('Solution design', $p.cap1t)
  $out = $out.Replace('Architecture and delivery plans aligned to your stack.', $p.cap1p)
  $out = $out.Replace('Production build', $p.cap2t)
  $out = $out.Replace('AI modules, APIs, and integrations ready to ship.', $p.cap2p)
  $out = $out.Replace('Operate &amp; improve', $p.cap3t)
  $out = $out.Replace('MLOps, monitoring, and handover for your team.', $p.cap3p)
  $faq1 = "<motion class=`"faq-item`"><h4>$($p.faq1q)</h4><p>$($p.faq1a)</p></div>"
  $faq1 = "<div class=`"faq-item`"><h4>$($p.faq1q)</h4><p>$($p.faq1a)</p></motion>"
  $faq1 = "<div class=`"faq-item`"><h4>$($p.faq1q)</h4><p>$($p.faq1a)</p></motion>"
  $faq2 = "<div class=`"faq-item`"><h4>$($p.faq2q)</h4><p>$($p.faq2a)</p></div>"
  $out = Set-Marker $out 'FAQ1' $faq1
  $out = Set-Marker $out 'FAQ2' $faq2
  $out = Set-Marker $out 'CTAT' $p.ctat
  $out = Set-Marker $out 'CTAP' $p.ctap
  $label = $p.city + ' AI'
  $out = $out.Replace('Custom AI development', $label)
  $out = $out.Replace('<motion class="silo-label">More AI services</div>', '<div class="silo-label">More locations</div>')
  $out = $out.Replace('<div class="silo-label">More AI services</motion>', '<div class="silo-label">More locations</div>')
  $out = $out.Replace('<div class="silo-label">More AI services</div>', '<motion class="silo-label">More locations</div>')
  $out = $out.Replace('<div class="silo-label">More industries</div>', '<div class="silo-label">More locations</div>')
  $silo = $p.siloLinks
  $out = [regex]::Replace($out, '(?s)<div class="silo-links">[\s\S]*?</div>', "<div class=`"silo-links`">`n$silo`n          </div>", 1)
  $tagsHtml = ($p.tags | ForEach-Object { "<span class=`"hero-tag`">$_</span>" }) -join "`n          "
  $out = [regex]::Replace($out, '(?s)<motion class="hero-tags">[\s\S]*?</div>', "<div class=`"hero-tags`">`n          $tagsHtml`n        </div>", 1)
  $out = [regex]::Replace($out, '(?s)<div class="hero-tags">[\s\S]*?</div>', "<div class=`"hero-tags`">`n          $tagsHtml`n        </div>", 1)
  $out = $out.Replace('<li><a href="ai-development-services.html" class="acesoft-nav-current-link">AI Development</a></li>', '<li><a href="ai-development-services.html" class="acesoft-nav-current-link">AI Development</a></li>')
  if ($out -notmatch 'ai-industries.html') {
    $out = $out.Replace('<li><a href="ai-staffing.html">AI Staffing</a></li>', '<li><a href="ai-staffing.html">AI Staffing</a></li>' + "`n								<li><a href=`"ai-industries.html`">Industries</a></li>")
  }
  $out = $out.Replace('generative-ai-development.html">Generative AI', ($p.hubSlug + '.html">' + $p.hubShort))
  $out = $out.Replace('llm-development.html">LLM Development', 'ai-development-services.html">AI Development')
  $out = $out.Replace('ai-agent-development.html">AI Agents', ($p.slug + '.html">' + $p.city))
  $out = $out.Replace('machine-learning-development.html">Machine Learning', 'page-contact.html">Contact')
  return $out
}

function New-Loc($slug,$title,$city,$hubSlug,$hubLabel,$hubShort,$icon,$hub,$meta,$intro,$h1,$answer,$h2,$b1,$b2,$b3,$b4,$focus,$cap1t,$cap1p,$cap2t,$cap2p,$cap3t,$cap3p,$faq1q,$faq1a,$faq2q,$faq2a,$ctat,$ctap,$tags,$siloLinks) {
  return [PSCustomObject]@{ slug=$slug; title=$title; city=$city; hubSlug=$hubSlug; hubLabel=$hubLabel; hubShort=$hubShort; icon=$icon; hub=$hub; meta=$meta; intro=$intro; h1=$h1; answer=$answer; h2=$h2; b1=$b1; b2=$b2; b3=$b3; b4=$b4; focus=$focus; cap1t=$cap1t; cap1p=$cap1p; cap2t=$cap2t; cap2p=$cap2p; cap3t=$cap3t; cap3p=$cap3p; faq1q=$faq1q; faq1a=$faq1a; faq2q=$faq2q; faq2a=$faq2a; ctat=$ctat; ctap=$ctap; tags=$tags; siloLinks=$siloLinks }
}

$caSiloHead = @"
            <a href="ai-development-canada.html">All Canada</a>
            <a href="ai-development-usa.html">USA locations</a>
"@
$usSiloHead = @"
            <a href="ai-development-usa.html">All USA</a>
            <a href="ai-development-canada.html">Canada locations</a>
"@

function Ca-Silo($extra) { return $caSiloHead + "`n" + $extra + "`n            <a href=`"ai-development-services.html`">AI development services</a>" }
function Us-Silo($extra) { return $usSiloHead + "`n" + $extra + "`n            <a href=`"ai-development-services.html`">AI development services</a>" }

$canada = @(
  (New-Loc 'ai-consultants-toronto' 'AI Consultants Toronto' 'Toronto' 'ai-development-canada' 'AI Development Canada' 'Canada' 'fa-building' 'AI consulting and development for GTA enterprises and startups.' 'AI consultants in Toronto. Custom AI, LLM apps, and automation by Acesoft for the Greater Toronto Area.' 'Acesoft helps Toronto teams ship production AI-from discovery in the financial district to deployment with enterprise governance.' 'AI Consultants in <em>Toronto</em><br>Built for GTA Teams' '<strong>Why hire AI consultants in Toronto?</strong> Local market knowledge plus Canadian-led engineering helps you move faster with compliant, scalable AI.' 'Toronto AI consulting for finance, healthcare, and product companies' 'Use-case workshops aligned to your KPIs' 'LLM, RAG, and automation delivery' 'Integration with Salesforce, Microsoft, and internal systems' 'Ongoing MLOps and model improvement' 'Toronto and GTA organizations building AI products or automating operations.' 'Discovery' 'Roadmaps and ROI models for your stack.' 'Build' 'Copilots, agents, and ML pipelines.' 'Operate' 'Monitoring, evals, and handover.' 'Do you work on-site in Toronto?' 'Yes-hybrid discovery and workshops in the GTA are available.' 'Can you support regulated industries?' 'We deliver with security, privacy, and audit patterns suited to financial and health clients.' 'Ready for AI consultants in Toronto?' 'Tell us your use case-we will propose a practical discovery and delivery plan.' @('Toronto AI','GTA','LLM &amp; RAG','Enterprise ready') (Ca-Silo '<a href="ai-consultant-london-ontario.html">London ON</a><a href="ai-consultants-vancouver.html">Vancouver</a><a href="ai-consultants-montreal.html">Montreal</a>')),
  (New-Loc 'ai-consultant-london-ontario' 'AI Consultant London Ontario' 'London' 'ai-development-canada' 'AI Development Canada' 'Canada' 'fa-map-marker' 'AI consulting and development for London, Ontario businesses and institutions.' 'AI consultant in London, Ontario. Custom AI development, LLM solutions, and automation by Acesoft.' 'Based in Southwestern Ontario, Acesoft partners with London organizations on AI strategy, build, and production operations-with local collaboration and North American delivery.' 'AI Consultant <em>London Ontario</em><br>Local Expertise, National Scale' '<strong>Why an AI consultant in London, ON?</strong> Work with a team that knows the regional ecosystem while delivering the same rigor as national programs.' 'AI consulting for London enterprises, startups, and public sector' 'On-site or hybrid discovery sessions' 'Custom copilots, automation, and ML' 'Secure cloud and on-prem options' 'Training and handover for your staff' 'London, Ontario and surrounding Southwestern Ontario.' 'Strategy' 'Prioritized use cases and architecture.' 'Delivery' 'Sprints to production-ready AI.' 'Support' 'MLOps and iteration after launch.' 'Is Acesoft located in London, Ontario?' 'Yes-we serve London and clients across Canada and the USA.' 'Do you support startups and enterprises?' 'Both-we scale engagement from MVP to enterprise rollout.' 'Ready to talk with an AI consultant in London?' 'Share your goals-we respond with a scoped next step when it is a fit.' @('London Ontario','Southwestern ON','Custom AI','Canadian team') (Ca-Silo '<a href="ai-consultants-toronto.html">Toronto</a><a href="ai-consultants-kitchener-waterloo.html">Kitchener-Waterloo</a><a href="ai-consultants-windsor.html">Windsor</a>')),
  (New-Loc 'ai-consultants-vancouver' 'AI Consultants Vancouver' 'Vancouver' 'ai-development-canada' 'AI Development Canada' 'Canada' 'fa-leaf' 'AI development and consulting for Vancouver and Lower Mainland companies.' 'AI consultants in Vancouver. Build LLM apps, automation, and ML systems with Acesoft.' 'Vancouver teams partner with Acesoft for AI product development, data pipelines, and responsible deployment across tech, natural resources, and services sectors.' 'AI Consultants <em>Vancouver</em><br>Pacific Coast Delivery' '<strong>How can Vancouver businesses use AI?</strong> From customer-facing copilots to back-office automation-we help you prove value and scale safely.' 'Vancouver AI consulting for tech and enterprise' 'Discovery aligned to BC privacy expectations' 'Product-grade LLM and ML engineering' 'Cloud-native and hybrid deployment' 'Continuous improvement after launch' 'Vancouver, Burnaby, Surrey, and Lower Mainland organizations.' 'Product AI' 'Features your users will adopt.' 'Data &amp; ML' 'Pipelines that stay reliable.' 'Governance' 'Guardrails and monitoring.' 'Do you collaborate Pacific time?' 'Yes-we align meetings and delivery to PT-friendly hours.' 'Remote or on-site?' 'Primarily remote with optional on-site workshops.' 'Ready for AI consultants in Vancouver?' 'Describe your product or process-we will outline options.' @('Vancouver AI','Lower Mainland','BC','LLM apps') (Ca-Silo '<a href="ai-consultants-toronto.html">Toronto</a><a href="ai-consultants-calgary.html">Calgary</a><a href="ai-consultants-ottawa.html">Ottawa</a>')),
  (New-Loc 'ai-consultants-montreal' 'AI Consultants Montreal' 'Montreal' 'ai-development-canada' 'AI Development Canada' 'Canada' 'fa-language' 'AI consulting in Montreal for bilingual product and operations teams.' 'AI consultants in Montreal. Bilingual AI development, LLM solutions, and automation by Acesoft.' 'Montreal organizations work with Acesoft on bilingual AI experiences, research-heavy ML, and enterprise integrations-with delivery in English and French.' 'AI Consultants <em>Montreal</em><br>Bilingual AI Delivery' '<strong>Why AI consultants in Montreal?</strong> Combine strong local talent markets with a partner that can ship bilingual, governed AI products.' 'Montreal AI for product, ops, and research teams' 'Bilingual UX and content workflows' 'LLM, RAG, and computer vision' 'Quebec and federal compliance awareness' 'Agile delivery with measurable KPIs' 'Greater Montreal enterprises, scale-ups, and institutions.' 'Experience' 'Copilots and customer AI in EN/FR.' 'Engineering' 'Production APIs and integrations.' 'Compliance' 'Privacy and access controls.' 'Do you build bilingual AI?' 'Yes-English and French experiences are a common requirement we support.' 'Can you work with our existing dev team?' 'We embed or deliver turnkey based on your preference.' 'Ready for AI consultants in Montreal?' 'Contact us with your use case and language requirements.' @('Montreal AI','Bilingual','Quebec','Enterprise') (Ca-Silo '<a href="ai-consultants-toronto.html">Toronto</a><a href="ai-consultants-ottawa.html">Ottawa</a><a href="ai-consultants-vancouver.html">Vancouver</a>')),
  (New-Loc 'ai-consultants-calgary' 'AI Consultants Calgary' 'Calgary' 'ai-development-canada' 'AI Development Canada' 'Canada' 'fa-industry' 'AI consulting for Calgary energy, logistics, and enterprise teams.' 'AI consultants in Calgary. Industrial AI, automation, and LLM solutions by Acesoft.' 'Calgary organizations use Acesoft for operational AI, document intelligence, and customer-facing assistants-grounded in your data and security needs.' 'AI Consultants <em>Calgary</em><br>Energy &amp; Enterprise AI' '<strong>What AI wins are common in Calgary?</strong> Document automation, forecasting, and field operations support often deliver fast ROI.' 'Calgary AI for energy, logistics, and SaaS' 'Operational discovery workshops' 'Predictive and generative solutions' 'Integration with ERP and field systems' 'Secure deployment patterns' 'Calgary and Alberta enterprises and growth companies.' 'Operations' 'Automation and decision support.' 'Analytics' 'Forecasting and anomaly detection.' 'Assistants' 'Staff and customer copilots.' 'Do you serve oil and gas use cases?' 'Yes-with appropriate security and data boundary design.' 'Alberta data residency?' 'We align architecture to your residency requirements.' 'Ready for AI consultants in Calgary?' 'Share your industry and systems-we will map a path.' @('Calgary AI','Alberta','Industrial AI','Automation') (Ca-Silo '<a href="ai-consultants-edmonton.html">Edmonton</a><a href="ai-consultants-toronto.html">Toronto</a><a href="ai-consultants-vancouver.html">Vancouver</a>')),
  (New-Loc 'ai-consultants-ottawa' 'AI Consultants Ottawa' 'Ottawa' 'ai-development-canada' 'AI Development Canada' 'Canada' 'fa-landmark' 'AI development and consulting for Ottawa-Gatineau public and private sector.' 'AI consultants in Ottawa. Secure AI for government and enterprise by Acesoft.' 'Ottawa teams rely on Acesoft for citizen-facing assistants, document automation, and analytics-with bilingual support and security-conscious delivery.' 'AI Consultants <em>Ottawa</em><br>Public &amp; Private Sector' '<strong>Why AI consultants in Ottawa?</strong> Experience with bilingual, security-tiered delivery suits federal, provincial, and tech clients in the capital region.' 'Ottawa AI for government and enterprise' 'Bilingual service design' 'Document and forms automation' 'Secure integration patterns' 'Audit-friendly logging and review' 'Ottawa-Gatineau agencies and technology companies.' 'Citizen &amp; user AI' 'Accessible assistants and search.' 'Back office' 'Classification and routing.' 'Governance' 'Human review and escalation.' 'Do you support government procurement?' 'We can align proposals to your procurement process.' 'English and French?' 'Yes-bilingual delivery is standard for Ottawa work.' 'Ready for AI consultants in Ottawa?' 'Describe your program and security needs.' @('Ottawa AI','Bilingual','Government','Secure AI') (Ca-Silo '<a href="ai-consultants-toronto.html">Toronto</a><a href="ai-consultants-montreal.html">Montreal</a><a href="ai-consultant-london-ontario.html">London ON</a>')),
  (New-Loc 'ai-consultants-kitchener-waterloo' 'AI Consultants Kitchener-Waterloo' 'Kitchener-Waterloo' 'ai-development-canada' 'AI Development Canada' 'Canada' 'fa-lightbulb-o' 'AI consulting for Kitchener-Waterloo tech corridor startups and enterprises.' 'AI consultants in Kitchener-Waterloo. Product AI, LLM apps, and MLOps by Acesoft.' 'The KW tech corridor partners with Acesoft to launch AI features fast-from MVP copilots to scalable platforms with solid engineering practices.' 'AI Consultants <em>Kitchener-Waterloo</em><br>Tech Corridor AI' '<strong>Why KW for AI development?</strong> Access senior AI engineering without slowing your product roadmap.' 'AI for KW startups and scale-ups' 'Lean discovery and MVP scoping' 'Full-stack AI product delivery' 'Investor-ready demos and metrics' 'Scale-up architecture when traction hits' 'Kitchener, Waterloo, Cambridge technology companies.' 'MVP' 'Ship core AI value in weeks.' 'Scale' 'Multi-tenant and cost controls.' 'Team' 'Staff aug or dedicated pod.' 'Can you work with our startup stack?' 'Yes-common clouds, repos, and CI/CD are supported.' 'Do you offer staff augmentation?' 'Yes-flexible models are available.' 'Ready for AI consultants in KW?' 'Share your product stage and timeline.' @('Kitchener-Waterloo','Tech corridor','Startups','MLOps') (Ca-Silo '<a href="ai-consultant-london-ontario.html">London ON</a><a href="ai-consultants-toronto.html">Toronto</a><a href="ai-consultants-windsor.html">Windsor</a>')),
  (New-Loc 'ai-consultants-windsor' 'AI Consultants Windsor' 'Windsor' 'ai-development-canada' 'AI Development Canada' 'Canada' 'fa-exchange' 'AI consulting for Windsor-Essex manufacturing and cross-border business.' 'AI consultants in Windsor, Ontario. Automation and AI for manufacturing and logistics by Acesoft.' 'Windsor-Essex companies work with Acesoft on plant-floor analytics, document AI, and customer operations-with cross-border collaboration experience.' 'AI Consultants <em>Windsor</em><br>Manufacturing &amp; Trade' '<strong>How does AI help Windsor businesses?</strong> Quality vision, scheduling, and document automation are frequent high-ROI starting points.' 'Windsor AI for manufacturing and logistics' 'OT/IT integration experience' 'Vision and predictive maintenance' 'Cross-border project coordination' 'Practical pilots with clear KPIs' 'Windsor-Essex manufacturers, logistics, and services.' 'Plant floor' 'Vision and anomaly detection.' 'Office ops' 'Document and email AI.' 'Customer' 'Support and scheduling bots.' 'Do you support US parent companies?' 'Yes-we routinely work with Canada-US stakeholders.' 'On-site plant visits?' 'Can be arranged for discovery and validation.' 'Ready for AI consultants in Windsor?' 'Tell us about your operations and data.' @('Windsor AI','Manufacturing','Cross-border','Automation') (Ca-Silo '<a href="ai-consultant-london-ontario.html">London ON</a><a href="ai-consultants-toronto.html">Toronto</a><a href="ai-consultants-kitchener-waterloo.html">KW</a>')),
  (New-Loc 'ai-consultants-edmonton' 'AI Consultants Edmonton' 'Edmonton' 'ai-development-canada' 'AI Development Canada' 'Canada' 'fa-cog' 'AI development and consulting for Edmonton enterprises and energy sector.' 'AI consultants in Edmonton. Industrial AI, LLM apps, and automation by Acesoft.' 'Edmonton organizations partner with Acesoft on operational AI, forecasting, and knowledge assistants designed for Alberta industries.' 'AI Consultants <em>Edmonton</em><br>Alberta AI Delivery' '<strong>Why AI consultants in Edmonton?</strong> Combine domain-aware discovery with engineering that scales beyond pilot.' 'Edmonton AI for energy, ag, and enterprise' 'Field and operations-focused discovery' 'ML forecasting and document AI' 'Secure hybrid deployment' 'Runbooks for internal teams' 'Edmonton and Northern Alberta businesses.' 'Operations AI' 'Scheduling and maintenance insights.' 'Knowledge' 'Search and copilots on your docs.' 'Analytics' 'Dashboards and alerts.' 'Remote collaboration?' 'Yes-with periodic on-site as needed.' 'Energy sector experience?' 'We have delivered automation and analytics for industrial clients.' 'Ready for AI consultants in Edmonton?' 'Share your priorities and systems landscape.' @('Edmonton AI','Alberta','Industrial','Knowledge AI') (Ca-Silo '<a href="ai-consultants-calgary.html">Calgary</a><a href="ai-consultants-vancouver.html">Vancouver</a><a href="ai-consultants-toronto.html">Toronto</a>')),
  (New-Loc 'ai-consultants-mississauga' 'AI Consultants Mississauga' 'Mississauga' 'ai-development-canada' 'AI Development Canada' 'Canada' 'fa-suitcase' 'AI consulting for Mississauga corporate and logistics headquarters.' 'AI consultants in Mississauga. Enterprise AI, automation, and LLM development by Acesoft.' 'Mississauga HQ teams choose Acesoft for AI programs that must integrate with enterprise ERP, CRM, and shared services at scale.' 'AI Consultants <em>Mississauga</em><br>Enterprise GTA AI' '<strong>Why AI consultants in Mississauga?</strong> Proximity to major corporate HQs with delivery built for enterprise integration and governance.' 'Mississauga enterprise AI programs' 'Stakeholder workshops and roadmaps' 'Copilots tied to ERP/CRM' 'Global rollout patterns' 'Service desk and ops automation' 'Mississauga-based enterprises and shared service centers.' 'Enterprise' 'Architecture and security reviews.' 'Integration' 'APIs into your core systems.' 'Rollout' 'Phased adoption and training.' 'Do you work with large enterprises?' 'Yes-enterprise governance is core to our delivery.' 'GTA on-site workshops?' 'Available for discovery and steering committees.' 'Ready for AI consultants in Mississauga?' 'Introduce your program sponsors and goals.' @('Mississauga AI','GTA enterprise','Integration','LLM') (Ca-Silo '<a href="ai-consultants-toronto.html">Toronto</a><a href="ai-consultants-ottawa.html">Ottawa</a><a href="ai-consultants-vancouver.html">Vancouver</a>'))
)

$usa = @(
  (New-Loc 'ai-consultants-new-york' 'AI Consultants New York' 'New York' 'ai-development-usa' 'AI Development USA' 'USA' 'fa-building' 'AI consulting for New York finance, media, and enterprise teams.' 'AI consultants in New York. LLM apps, automation, and enterprise AI by Acesoft.' 'New York organizations work with Acesoft on high-stakes AI-copilots, research automation, and customer experiences with strong governance.' 'AI Consultants <em>New York</em><br>Enterprise-Grade AI' '<strong>Why AI consultants in New York?</strong> Fast discovery and delivery for complex, regulated environments.' 'NYC AI for finance, media, and SaaS' 'Executive-aligned roadmaps' 'LLM and agent engineering' 'SOC-aware delivery practices' 'Production monitoring and evals' 'Manhattan and NYC metro enterprises and startups.' 'Strategy' 'Use-case portfolio and KPIs.' 'Build' 'Secure copilots and workflows.' 'Scale' 'Cost and reliability tuning.' 'US time zone overlap?' 'We align to Eastern hours for US clients.' 'On-site in NYC?' 'Workshops can be scheduled; delivery is often hybrid.' 'Ready for AI consultants in New York?' 'Share your sector and timeline.' @('New York AI','NYC','Finance','Enterprise LLM') (Us-Silo '<a href="ai-consultants-boston.html">Boston</a><a href="ai-consultants-chicago.html">Chicago</a><a href="ai-consultants-san-francisco.html">San Francisco</a>')),
  (New-Loc 'ai-consultants-san-francisco' 'AI Consultants San Francisco' 'San Francisco' 'ai-development-usa' 'AI Development USA' 'USA' 'fa-code' 'AI development for Bay Area startups and technology companies.' 'AI consultants in San Francisco. Product AI, LLM features, and MLOps by Acesoft.' 'Bay Area teams partner with Acesoft to ship AI-native product features with solid evals, cost controls, and integration into modern stacks.' 'AI Consultants <em>San Francisco</em><br>Bay Area Product AI' '<strong>How do SF teams ship AI faster?</strong> Senior LLM engineering plus product discipline reduces rework and speeds launches.' 'San Francisco AI product development' 'Technical discovery with your PM and eng leads' 'RAG, agents, and fine-tuning when needed' 'Usage metering and guardrails' 'Post-launch optimization' 'San Francisco and Bay Area technology companies.' 'Product' 'Features users adopt.' 'Platform' 'APIs and eval harnesses.' 'Ops' 'Monitoring and spend controls.' 'Pacific time collaboration?' 'Yes-regular overlap with PT schedules.' 'Startup-friendly engagements?' 'MVPs and scale-up support are common.' 'Ready for AI consultants in San Francisco?' 'Tell us about your product and stack.' @('San Francisco AI','Bay Area','Product AI','Startups') (Us-Silo '<a href="ai-consultants-new-york.html">New York</a><a href="ai-consultants-seattle.html">Seattle</a><a href="ai-consultants-los-angeles.html">Los Angeles</a>')),
  (New-Loc 'ai-consultants-los-angeles' 'AI Consultants Los Angeles' 'Los Angeles' 'ai-development-usa' 'AI Development USA' 'USA' 'fa-film' 'AI consulting for Los Angeles media, entertainment, and enterprise.' 'AI consultants in Los Angeles. Content AI, automation, and LLM apps by Acesoft.' 'LA organizations use Acesoft for media workflows, customer AI, and back-office automation-with rights-aware guardrails where needed.' 'AI Consultants <em>Los Angeles</em><br>Media &amp; Enterprise AI' '<strong>Why AI consultants in LA?</strong> Creative and operational AI with controls suited to content-heavy industries.' 'Los Angeles AI for media and enterprise' 'Workflow mapping for creative ops' 'Metadata, search, and generation pipelines' 'Brand safety and review queues' 'Analytics on adoption and quality' 'Los Angeles metro media, retail, and services.' 'Content' 'Tagging, search, and repurposing.' 'Customer' 'Support and sales assistants.' 'Ops' 'Scheduling and document AI.' 'Rights-managed content?' 'Yes-access and approval flows are built in.' 'Remote delivery to LA?' 'Yes-we collaborate effectively across time zones.' 'Ready for AI consultants in Los Angeles?' 'Describe your content or ops challenge.' @('Los Angeles AI','Media','Content AI','Enterprise') (Us-Silo '<a href="ai-consultants-san-francisco.html">San Francisco</a><a href="ai-consultants-seattle.html">Seattle</a><a href="ai-consultants-austin.html">Austin</a>')),
  (New-Loc 'ai-consultants-chicago' 'AI Consultants Chicago' 'Chicago' 'ai-development-usa' 'AI Development USA' 'USA' 'fa-industry' 'AI consulting for Chicago manufacturing, logistics, and enterprise.' 'AI consultants in Chicago. Industrial AI, automation, and LLM solutions by Acesoft.' 'Chicago teams rely on Acesoft for supply chain AI, document processing, and customer operations across the Midwest.' 'AI Consultants <em>Chicago</em><br>Midwest Enterprise AI' '<strong>What AI fits Chicago industries?</strong> Logistics optimization, quality analytics, and knowledge search are strong starters.' 'Chicago AI for manufacturing and services' 'Operations-focused discovery' 'Forecasting and document intelligence' 'ERP and WMS integrations' 'Measurable pilot KPIs' 'Chicago and Midwest enterprises.' 'Supply chain' 'Planning and exception management.' 'Quality' 'Vision and SPC support.' 'Knowledge' 'Copilots on manuals and policies.' 'Central time overlap?' 'Yes-we align to US Central and Eastern.' 'On-site in Chicago?' 'Discovery workshops can be arranged.' 'Ready for AI consultants in Chicago?' 'Share your operations and data sources.' @('Chicago AI','Midwest','Logistics','Manufacturing') (Us-Silo '<a href="ai-consultants-new-york.html">New York</a><a href="ai-consultants-dallas.html">Dallas</a><a href="ai-consultants-atlanta.html">Atlanta</a>')),
  (New-Loc 'ai-consultants-boston' 'AI Consultants Boston' 'Boston' 'ai-development-usa' 'AI Development USA' 'USA' 'fa-flask' 'AI consulting for Boston healthcare, biotech, and technology.' 'AI consultants in Boston. Regulated AI, LLM apps, and ML by Acesoft.' 'Boston organizations partner with Acesoft on research acceleration, clinical ops support, and product AI-with compliance in mind.' 'AI Consultants <em>Boston</em><br>Health &amp; Tech AI' '<strong>Why AI consultants in Boston?</strong> Experience with research-heavy and regulated environments accelerates trustworthy delivery.' 'Boston AI for health, biotech, and SaaS' 'Compliance-aware discovery' 'Document and literature intelligence' 'Clinical and ops workflow automation' 'Validation and monitoring' 'Greater Boston life sciences and technology.' 'Research' 'Summarization and extraction.' 'Operations' 'Workflow and routing AI.' 'Product' 'User-facing assistants with guardrails.' 'HIPAA-aligned patterns?' 'Yes-we design for healthcare privacy requirements.' 'Work with academic partners?' 'We can collaborate under your IP and data agreements.' 'Ready for AI consultants in Boston?' 'Outline your regulatory context and use case.' @('Boston AI','Healthcare','Biotech','LLM') (Us-Silo '<a href="ai-consultants-new-york.html">New York</a><a href="ai-consultants-chicago.html">Chicago</a><a href="ai-consultants-seattle.html">Seattle</a>')),
  (New-Loc 'ai-consultants-austin' 'AI Consultants Austin' 'Austin' 'ai-development-usa' 'AI Development USA' 'USA' 'fa-music' 'AI development for Austin startups and enterprise technology.' 'AI consultants in Austin. Product AI, agents, and cloud ML by Acesoft.' 'Austin tech companies work with Acesoft to add AI to SaaS products and internal tools with pragmatic architecture and fast iteration.' 'AI Consultants <em>Austin</em><br>Texas Tech AI' '<strong>How do Austin startups adopt AI?</strong> Start with a focused MVP, measure usage, then scale infrastructure and governance.' 'Austin AI for SaaS and enterprise IT' 'Lean product discovery' 'Agent and copilot features' 'AWS-friendly deployment' 'Cost and latency optimization' 'Austin and Central Texas technology companies.' 'MVP' 'Ship in weeks, not months.' 'Integrate' 'APIs into your app.' 'Grow' 'Scale when metrics prove value.' 'Central time collaboration?' 'Yes-regular US hours overlap.' 'Dedicated team models?' 'Pods and staff augmentation available.' 'Ready for AI consultants in Austin?' 'Share your product and cloud stack.' @('Austin AI','Texas','SaaS','Agents') (Us-Silo '<a href="ai-consultants-dallas.html">Dallas</a><a href="ai-consultants-san-francisco.html">San Francisco</a><a href="ai-consultants-atlanta.html">Atlanta</a>')),
  (New-Loc 'ai-consultants-seattle' 'AI Consultants Seattle' 'Seattle' 'ai-development-usa' 'AI Development USA' 'USA' 'fa-cloud' 'AI consulting for Seattle cloud, retail, and technology leaders.' 'AI consultants in Seattle. Cloud AI, LLM products, and MLOps by Acesoft.' 'Seattle organizations choose Acesoft for AI on Azure/AWS, ecommerce intelligence, and developer productivity copilots.' 'AI Consultants <em>Seattle</em><br>Pacific Northwest AI' '<strong>Why AI consultants in Seattle?</strong> Deep cloud engineering plus product AI helps PNW teams ship reliably.' 'Seattle AI for cloud and retail tech' 'Cloud-native architecture' 'Copilots for engineering and support' 'Data platform integration' 'FinOps-friendly model routing' 'Seattle metro technology and retail enterprises.' 'Cloud AI' 'Secure VPC patterns.' 'Product' 'Customer and internal features.' 'MLOps' 'Evals, drift, and retraining.' 'Pacific time meetings?' 'Yes-we align to PT for US West clients.' 'Enterprise security reviews?' 'We provide artifacts for InfoSec early.' 'Ready for AI consultants in Seattle?' 'Describe your cloud and compliance needs.' @('Seattle AI','Pacific NW','Cloud','MLOps') (Us-Silo '<a href="ai-consultants-san-francisco.html">San Francisco</a><a href="ai-consultants-los-angeles.html">Los Angeles</a><a href="ai-consultants-boston.html">Boston</a>')),
  (New-Loc 'ai-consultants-dallas' 'AI Consultants Dallas' 'Dallas' 'ai-development-usa' 'AI Development USA' 'USA' 'fa-line-chart' 'AI consulting for Dallas-Fort Worth enterprise and energy.' 'AI consultants in Dallas. Enterprise AI, automation, and analytics by Acesoft.' 'DFW organizations partner with Acesoft on shared-services automation, sales intelligence, and operational AI at enterprise scale.' 'AI Consultants <em>Dallas</em><br>DFW Enterprise AI' '<strong>What drives AI ROI in Dallas?</strong> Automating high-volume back-office work and improving forecast accuracy.' 'Dallas AI for enterprise and energy' 'Stakeholder alignment workshops' 'Document and email intelligence' 'CRM and ERP-connected copilots' 'Phased enterprise rollout' 'Dallas-Fort Worth headquarters and regional ops.' 'Automation' 'Back-office throughput gains.' 'Revenue' 'Sales and service assistants.' 'Insights' 'Forecasting and dashboards.' 'Central time support?' 'Yes-full overlap with Texas business hours.' 'Multi-BU rollouts?' 'We plan phased adoption across units.' 'Ready for AI consultants in Dallas?' 'Introduce your enterprise sponsors.' @('Dallas AI','DFW','Enterprise','Automation') (Us-Silo '<a href="ai-consultants-austin.html">Austin</a><a href="ai-consultants-chicago.html">Chicago</a><a href="ai-consultants-atlanta.html">Atlanta</a>')),
  (New-Loc 'ai-consultants-atlanta' 'AI Consultants Atlanta' 'Atlanta' 'ai-development-usa' 'AI Development USA' 'USA' 'fa-plane' 'AI consulting for Atlanta logistics, fintech, and enterprise.' 'AI consultants in Atlanta. Automation, LLM apps, and ML by Acesoft.' 'Atlanta teams work with Acesoft on logistics AI, customer service automation, and analytics for Southeast US operations.' 'AI Consultants <em>Atlanta</em><br>Southeast US AI' '<strong>Why AI consultants in Atlanta?</strong> Hub for logistics and enterprise HQs needing scalable AI programs.' 'Atlanta AI for logistics and enterprise' 'Network and ops discovery' 'Routing and demand signals' 'Support and sales copilots' 'Integration with major SaaS stacks' 'Atlanta metro enterprises and growth companies.' 'Logistics' 'Planning and ETA intelligence.' 'Service' 'Contact center AI assist.' 'Growth' 'Analytics for revenue teams.' 'Eastern time collaboration?' 'Yes-aligned to US Eastern hours.' 'Pilot-to-production?' 'We define milestones from pilot through scale.' 'Ready for AI consultants in Atlanta?' 'Share your industry and KPIs.' @('Atlanta AI','Southeast US','Logistics','Enterprise') (Us-Silo '<a href="ai-consultants-miami.html">Miami</a><a href="ai-consultants-dallas.html">Dallas</a><a href="ai-consultants-new-york.html">New York</a>')),
  (New-Loc 'ai-consultants-miami' 'AI Consultants Miami' 'Miami' 'ai-development-usa' 'AI Development USA' 'USA' 'fa-sun-o' 'AI consulting for Miami finance, hospitality, and international business.' 'AI consultants in Miami. Multilingual AI, automation, and LLM apps by Acesoft.' 'Miami organizations use Acesoft for bilingual customer AI, real estate ops, and financial services automation across the Americas.' 'AI Consultants <em>Miami</em><br>Americas-Facing AI' '<strong>How does AI help Miami businesses?</strong> Bilingual service, faster onboarding, and document automation for international clients.' 'Miami AI for finance, travel, and real estate' 'Multilingual conversation design' 'KYC and document extraction' 'Customer messaging automation' 'Reporting for compliance teams' 'Miami-Dade and South Florida enterprises.' 'Customer AI' 'Chat and voice assistants.' 'Documents' 'Intake and verification.' 'Ops' 'Scheduling and routing.' 'Spanish and English?' 'Yes-multilingual experiences are supported.' 'Latin America coordination?' 'We work with distributed stakeholders across time zones.' 'Ready for AI consultants in Miami?' 'Tell us your markets and languages.' @('Miami AI','Bilingual','Finance','Hospitality') (Us-Silo '<a href="ai-consultants-atlanta.html">Atlanta</a><a href="ai-consultants-new-york.html">New York</a><a href="ai-consultants-austin.html">Austin</a>'))
)

function Build-Hub($hubSlug, $hubTitle, $metaDesc, $eyebrow, $h1Line1, $h1Em, $lead, $tags, $hubLabel, $gridClass, $sectionLabel, $sectionH3, $sectionP, $locations, $navActive) {
  $hubSrc = Join-Path $root 'ai-industries.html'
  $hub = [System.IO.File]::ReadAllText($hubSrc, $utf8)
  $hub = $hub.Replace('ai-industries.html', $hubSlug)
  $hub = $hub.Replace('AI Solutions by Industry | Sector-Specific AI | Acesoft', $hubTitle)
  $hub = $hub.Replace('Industry-specific AI solutions for healthcare, finance, retail, logistics, and more. Acesoft builds secure, production-ready AI for your sector in Canada and the USA.', $metaDesc)
  $hub = $hub.Replace('og:title" content="AI Solutions by Industry | Acesoft Canada"', ('og:title" content="' + $hubTitle + '"'))
  $hub = $hub.Replace('twitter:title" content="AI Solutions by Industry | Acesoft Canada"', ('twitter:title" content="' + $hubTitle + '"'))
  $hub = $hub.Replace('AI Solutions by Industry', $eyebrow)
  $hub = $hub.Replace('Industry-Specific AI<br>', ($h1Line1 + '<br>'))
  $hub = $hub.Replace('<em>Built for Your Sector</em>', ('<em>' + $h1Em + '</em>'))
  $hub = $hub.Replace('From healthcare and finance to retail and manufacturing-Acesoft delivers AI that respects your regulations, data, and operating model.', $lead)
  $hub = $hub.Replace('id="aiIndustriesHub"', ('id="' + $hubSlug.Replace('.html','') + 'Hub"'))
  $hub = $hub.Replace('Industries We Serve', $sectionLabel)
  $hub = $hub.Replace('Explore AI Solutions by Industry', $sectionH3)
  $hub = $hub.Replace('Each industry has a dedicated page with use cases, deliverables, and how Acesoft can help your team in Canada and beyond.', $sectionP)
  $hub = $hub.Replace('seo-service-grid seo-service-grid--industries', ('seo-service-grid ' + $gridClass))
  $hub = $hub.Replace('View industry', 'View location')
  $hubCards = ($locations | ForEach-Object {
    "            <a href=`"$($_.slug).html`" class=`"seo-service-card`"><span class=`"seo-service-card-icon`"><i class=`"fa $($_.icon)`"></i></span><h4>$($_.title)</h4><p>$($_.hub)</p><span class=`"seo-service-card-link`">View location</span></a>"
  }) -join "`n"
  $hub = [regex]::Replace($hub, '(?s)<div class="seo-service-grid[^"]*">[\s\S]*?</div>\s*</motion>\s*</motion>', "<div class=`"seo-service-grid $gridClass`">`n$hubCards`n          </div>", 1)
  $hub = [regex]::Replace($hub, '(?s)<div class="seo-service-grid[^"]*">[\s\S]*?</motion>\s*</motion>', "<div class=`"seo-service-grid $gridClass`">`n$hubCards`n          </div>", 1)
  $hub = [regex]::Replace($hub, '(?s)<div class="seo-service-grid[^"]*">[\s\S]*?</motion>\s*</div>\s*</div>', "<div class=`"seo-service-grid $gridClass`">`n$hubCards`n          </motion>", 1)
  $hub = [regex]::Replace($hub, '(?s)<div class="seo-service-grid[^"]*">[\s\S]*?</div>\s*</div>', "<div class=`"seo-service-grid $gridClass`">`n$hubCards`n          </div>", 1)
  if ($navActive -eq 'development') {
    $hub = $hub.Replace('<li><a href="ai-industries.html" class="acesoft-nav-current-link">Industries</a></li>', '<li><a href="ai-industries.html">Industries</a></li>')
    $hub = $hub.Replace('<li><a href="ai-development-services.html">AI Development</a></li>', '<li><a href="ai-development-services.html" class="acesoft-nav-current-link">AI Development</a></li>')
  }
  [System.IO.File]::WriteAllText((Join-Path $root $hubSlug), $hub, $utf8)
  Write-Host "Created $hubSlug"
}

Build-Hub 'ai-development-canada.html' 'AI Development Canada | AI Consultants & Developers | Acesoft' 'AI development and consulting across Canada. Explore city-specific AI consultant pages for Toronto, Vancouver, Montreal, London ON, and more.' 'AI Development Canada' 'AI Development' 'Across Canada' 'Canadian-led AI engineering for enterprises and startups-city-specific consultants, secure delivery, and production MLOps from Acesoft.' @('Toronto','London ON','Vancouver','Montreal','Canada-wide') 'Locations' 'seo-service-grid--locations' 'Cities We Serve' 'AI Consultants &amp; Development by City' 'Find AI consultants and development support in major Canadian markets-each page covers local delivery, use cases, and how Acesoft can help.' $canada 'development'

Build-Hub 'ai-development-usa.html' 'AI Development USA | AI Consultants & Developers | Acesoft' 'AI development and consulting across the United States. City pages for New York, San Francisco, Chicago, Boston, Austin, and more.' 'AI Development USA' 'AI Development' 'Across the USA' 'US-friendly collaboration with senior AI engineers-LLM products, automation, and enterprise programs delivered by Acesoft.' @('New York','San Francisco','Chicago','Boston','US-wide') 'Locations' 'seo-service-grid--locations' 'Cities We Serve' 'AI Consultants &amp; Development by City' 'Explore AI consultant and development pages for major US metros-local context, delivery models, and engagement options.' $usa 'development'

$template = [System.IO.File]::ReadAllText((Join-Path $root 'custom-ai-development-services.html'), $utf8)
foreach ($p in ($canada + $usa)) {
  $page = Build-LocationPage $p $template
  [System.IO.File]::WriteAllText((Join-Path $root ($p.slug + '.html')), $page, $utf8)
  Write-Host "Created $($p.slug).html"
}

$sitemapPath = Join-Path $root 'sitemap.xml'
$sitemap = [System.IO.File]::ReadAllText($sitemapPath, $utf8)
if ($sitemap -notmatch 'ai-development-canada.html') {
  $insert = "  <url>`n    <loc>https://www.aidevelopers.ca/ai-development-canada.html</loc>`n  </url>`n  <url>`n    <loc>https://www.aidevelopers.ca/ai-development-usa.html</loc>`n  </url>`n"
  foreach ($p in ($canada + $usa)) {
    $insert += "  <url>`n    <loc>https://www.aidevelopers.ca/$($p.slug).html</loc>`n  </url>`n"
  }
  $sitemap = $sitemap.Replace('</urlset>', ($insert + '</urlset>'))
  [System.IO.File]::WriteAllText($sitemapPath, $sitemap, $utf8)
  Write-Host 'Updated sitemap.xml'
}

Write-Host 'Location setup complete'
